audit_header: false
title: Fayetteville Real Estate Video Blog with Deana Watson
description: Our mission at Keller Williams Fayetteville is to be your best resource for Fayetteville real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Keller Williams Fayetteville, your professional Fayetteville Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Deana Watson
  title:
  license_number: License# 278531
  about_markdown: |
    We are The Signature Group, a team made up of a handful of experienced real estate agents and three hardworking admin personnel. We not only sell homes but also build relationships formed between our team and our clients. Our priorities are trust, teamwork, bold vision and a true focus on our clients. We look forward to working with you in your home buying or selling process!
  brand: Keller Williams Fayetteville
  brokerage:
  market: Fayetteville
  address: 639 Executive Pl Suite 100 Fayetteville, NC 28305
  phone: 615-584-0377
  phone_type:
  phone2:
  phone2_type:
  email: deana@signaturegroupteam.com
  url: https://deana.ftbraggnchomefinder.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://deana.ftbraggnchomefinder.com/property-report/
  second_CTA_text: Home Search
  second_CTA_URL: https://deana.ftbraggnchomefinder.com/results-gallery/?county=5352&sort=importdate&status=A

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Fayetteville Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://deana.ftbraggnchomefinder.com/property-report/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Fayetteville Home?"
    CTA_text2: "Search the entire MLS for your Fayetteville home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://deana.ftbraggnchomefinder.com/results-gallery/?county=5352&sort=importdate&status=A

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thesignaturegrouprealtyteam/
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Fayetteville Real Estate Podcast with Deana Watson'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Fayetteville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams Fayetteville - your professional Fayetteville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Fayetteville, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Deana Watson'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#449F8E'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: white
  button_text_color: '#449F8E'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
